
---
- name: Install Apache
  hosts: all
  become: yes
  
  vars:
    source_folder: ./MyWebSite/index.html     #FOLDER
    destion_folder: /var/www/html             #FOLDER
  
  tasks:
  - name: Check and Print Linux Version
    debug: var=ansible_os_family
    
  - block: #=========RedHat===========  
    
    - name: Install Apache WebServer
      yum: name=httpd state=latest
      
    - name: Start and Enable Apache
      service: name=httpd state=started enabled=yes
    
    when: ansible_os_family == "RedHat"
   

  - block: #=========Ubuntu===========  
    
    - name: Install Apache WebServer
      yum: name=apache2 state=latest
      
    - name: Start and Enable Apache
      service: name=apache2 state=started enabled=yes
    
    when: ansible_os_family == "Debian"
    
  - name: Copy MyHomePage to Servers
    copy: src={{ source_folder }}/{{ item }}  dest={{ destion_folder }} mode=0555
    loop:
        - "index.html"
        - "1.png"
        - "2.png"
        - "3.png"
        - "4.png"
    notify: 
        - Restart Apache RedHat
        - Restart Apache Debian


   
  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted
    
  - name: Restart Apache Debian
    service: name=apache2 state=restarted