
---
- name: Install Apache
  hosts: all
  become: yes
  
  vars:
    source_file: ./MyWebSite/index.html
    destion_file: /var/www/html
  
  tasks:
  - name: Install Apache WebServer
    yum: name=httpd state=latest
    
  - name: Copy MyHomePage to Servers
    copy: src={{ source_file }}  dest={{ destion_file }} mode=0555
    notify: Restart Apache      # Если была замена файла применяться будет handlers
    
  handlers:
  - name: Restart Apache
    service: name=httpd state=restarted
    
  - name: Start and Enable Apache
    service: name=httpd state=started enabled=yes